### ISSUE TITLE
cli if skip tls certificate verification

### ISSUE THREAD

**Issue by fengshunli** [nats-io/natscli#540] opened 2022-07-25 04:00 UTC
<img width="758" alt="image" src="https://user-images.githubusercontent.com/18587688/180696261-45a3d725-d9ac-4204-b280-15de2dd25927.png">

**Comment by ripienaar** [comment] 2022-08-05 10:50
dupe of https://github.com/nats-io/natscli/issues/181

verificatin is require at present

**Closed by ripienaar** 2022-08-05 10:50 UTC
