### ISSUE TITLE
`nats sub` doesn't show published data

### ISSUE THREAD

**Issue by apollo13** [nats-io/natscli#1198] opened 2024-12-13 09:44 UTC
### Observed behavior

I am running a server like this `nats-server -D -V` (version 2.10.9) and having a subscription:
```
$ nats sub test --match-replies
10:27:40 Matching replies with inbox prefix _INBOX.>
10:27:40 Subscribing on test 
```
now a `nats req test yolo` times out and the subscription shows nothing.

### Expected behavior

I would expect something like:
```
[#3] Received on "test" with reply "_INBOX..."
yolo
```
to show up

### Server and client version

nats-server: v2.10.9
client: 0.1.5

### Host environment

Fedora 41, amd64

### Steps to reproduce

```
nats-server -D -V
nats sub test --match-replies
nats req test yolo
```

**Comment by ripienaar** [comment] 2024-12-13 10:10
Ah, I get what's happening - its confusing but working as intended.

When you do `nats sub` its not going to be replying to anything, it's just passively listening.  `nats req` though expects a reply and `--match-replies` also expects a reply FROM SOMETHING ELSE.

So if you did 3 terminals:

```
$ nats reply test test
$ nats sub test --match-replies
$ nats req test test
```

Now you'll get the responses you want - the point is `nats sub --match-replies` spies on conversations being had by 2 other entities and to work there must be something replying

So I'll close this as working, but feel free to ask followup questions

**Closed by ripienaar** 2024-12-13 10:10 UTC
Labels: defect
