### ISSUE TITLE
natscli help

### ISSUE THREAD

**Issue by aricart** [nats-io/natscli#343] opened 2022-02-03 15:51 UTC
The help command is overwhelming - Not sure how we can fix this given that the command lib we are using is simply managing flags, rather than grouping different command hierarchies together w/ their relevant help (https://github.com/spf13/cobra does this well).

At the very least perhaps the help should be constrained to direct command or subcommands?

**Comment by ripienaar** [comment] 2022-02-03 16:04
dupe of #330

**Closed by ripienaar** 2022-02-03 16:04 UTC
